In [1]:
import numpy as np

In [2]:
a=np.ones(shape=(3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
b=np.ones(shape=(3,3))*2
b

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [4]:
a+b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [5]:
a*b

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [6]:
a.dot(b)

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [7]:
a@b

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [9]:
a.shape

(3, 3)

In [12]:
c=np.ones(shape=(3,1))*2
c

array([[2.],
       [2.],
       [2.]])

In [11]:
c.sum()

3.0

In [14]:
(c**2).sum()

12.0

In [16]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [20]:
np.ravel(x,order='C')

array([1, 2, 3, 4, 5, 6])

In [21]:
np.ravel(x,order='F')

array([1, 4, 2, 5, 3, 6])

In [22]:
np.ravel(x,order='A')

array([1, 2, 3, 4, 5, 6])

In [26]:
x.ravel().shape

(6,)

In [30]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
c=np.ones(shape=(3,1))*2

In [32]:
c

array([[2.],
       [2.],
       [2.]])

In [33]:
c**2

array([[4.],
       [4.],
       [4.]])

In [34]:
c*c

array([[4.],
       [4.],
       [4.]])

In [36]:
m1=np.matrix(data=c)
m2=np.matrix(data=c)

In [37]:
m1

matrix([[2.],
        [2.],
        [2.]])

In [38]:
m2

matrix([[2.],
        [2.],
        [2.]])

In [40]:
m1.T*m2

matrix([[12.]])

In [42]:
m1.T@m2

matrix([[12.]])